### Get Movies
GET http://172.16.3.35:8080/movies HTTP/1.1

### Get Movies with filters
# movieName - movieYear - director - genre
GET http://172.16.3.35:8080/movies?movieName=Avatar&movieYear=2009 HTTP/1.1

### get movie by id
# example id movie 23
GET http://172.16.3.35:8080/movies/23 HTTP/1.1

### Add movie
POST http://172.16.3.35:8080/movies HTTP/1.1
content-type: application/json

{
  "name": "Avatar",
  "year": 2009,
  "director": "James Cameron",
  "genre": "action",
  "description": "A paraplegic Marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home."
}

### Update movie
PUT http://172.16.3.35:8080/movies HTTP/1.1
content-type: application/json

{
  "id": 23,
  "name": "Avatar",
  "year": 2009,
  "director": "James Cameron",
  "genre": "action",
  "description": "A paraplegic Marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home."
}

### Delete movie
DELETE http://172.16.3.35:8080/movies/23 HTTP/1.1